name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint

      - run: pnpm test

      - name: Publish to npm
        run: |
          VERSION=$(node -p "require('./package.json').version")
          case $VERSION in
            *-alpha.*) TAG="alpha" ;;
            *-beta.*)  TAG="beta" ;;
            *-rc.*)    TAG="next" ;;
            *)         TAG="latest" ;;
          esac
          pnpm publish --access public --no-git-checks --tag $TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
